---
title: "MCMC Diagnostics - Extension to results from 5/1"
author: "Sarah Teichman"
date: "05/06/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bayesplot)
library(rstan)
library(tidyverse)
load("fit_ifls_4-30.rda")
```

```{r, echo = F}
K <- 7
Ti <- 3
N <- 1973
fit <- fit_ifls
```


### Individual Parameter Diagnostics 

Reduce posterior to only runs where the absolute value of $\beta$ is greater than 30. 

```{r, echo = F}
draws <- as.matrix(fit)
beta_col <- which(colnames(draws) == "beta")
ind <- which(draws[,beta_col] > 15)
ext_pos_draws <- draws[ind, ]
ind <- which(draws[,beta_col] < -15)
ext_neg_draws <- draws[ind, ]
fit_summ <- as.data.frame(summary(fit)$summary)
```

Individual parameter plots. Autocorrelation and trace plots for individual parameters, and histograms of posterior medians for group parameters. 

```{r, echo = F}
sigma_params <- sort(grep("sigma",row.names(fit_summ), value=T)[1:22])[1:11]
beta <- "beta"
gamma <- "gamma"
```

```{r, echo = F}
get_single_plots <- function(fit, param) { 
  print(fit_summ[param,c(1,2,3,5,6,7,9,10)])
  print(rstan::traceplot(fit, pars = param))
  len <- length(param) 
  for (i in 1:len) {
    title = param[i]
    print(plot(ext_draws[,param[i]], type = "l", main = title))
  }
} 
get_aggreg_plots <- function(fit, param, trim = F, trim_amount) {
  ind <- grep(paste0("^",param), rownames(as.data.frame(summary(fit)$summary)))
  medians <- data.frame(avg = as.data.frame(summary(fit)$summary)$`50%`[ind])
  #print(paste0("Summary statistics for posterior medians of ",param))
  #print(summary(medians))
  title <- paste0("Posterior Medians of ",param)
  print(ggplot(medians, aes(x = avg)) + geom_histogram(bins = 60) + ggtitle(title))
  get_median <- function(x) {return(median(x))}
  ext_pos_medians <- data.frame(med = apply(ext_pos_draws[,ind], 2, get_median))
  title <- paste0("Posterior Medians of ",param, " for large positive beta")
  print(ggplot(ext_pos_medians, aes(x = med)) + geom_histogram(bins = 60) + ggtitle(title))
  ext_neg_medians <- data.frame(med = apply(ext_neg_draws[,ind], 2, get_median))
  title <- paste0("Posterior Medians of ",param, " for large negative beta")
  print(ggplot(ext_neg_medians, aes(x = med)) + geom_histogram(bins = 60) + ggtitle(title))
}
plot_fit <- function(fit) {
  #get_single_plots(fit, sigma_params)
  #get_single_plots(fit, beta)
  #get_single_plots(fit, gamma)
  get_aggreg_plots(fit, "w")
  get_aggreg_plots(fit, "z")
  get_aggreg_plots(fit, "p")
}
plot_fit(fit)
```


