---
title: "Latent space quantiles"
author: "Sarah Teichman"
date: "05/19/20"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bayesplot)
library(rstan)
library(tidyverse)
library(splitstackshape)
library(stringi)
library(parallelDist)
library(labdsv)
library(ape)
load("fit_ifls_5-15.rda")
load("deflate_y_dat.rda")
```

```{r,echo=F}
fit <- fit_ifls
dat <- deflate_y_dat
post <- as.data.frame(fit)
fit_summ <- as.data.frame(summary(fit)$summary)
```

```{r,echo=F}
K <- 7
Ti <- 3
N <- 1973
labs <- c("Agriculture","Manufacturing","Construction","Hospitality",
          "Transportation","Business","Social Services")
```


```{r, echo = F}
log_y <- log(dat$y)
job <- array(data = NA, dim = c(N,Ti))
for (i in 1:N) {
  for (t in 1:Ti) {
    job[i,t] <- which(dat$a[i,t,]==1)
  }
}
wage_job_dat <- data.frame(worker = rep(1:N,3), time = sort(rep(1:3,N)),
                            log_wage = c(log_y[,1],log_y[,2],log_y[,3]),
                            job = c(job[,1],job[,2],job[,3])) %>%
  mutate(job = labs[job])
```


```{r,echo=F}
med_z <- data.frame(par = rownames(fit_summ), med = fit_summ[,4]) %>%
  filter(grepl("z\\[", par)) %>%
  cSplit("par",direction = "wide") %>%
  mutate(worker = stri_extract_first_regex(par_1,"[0-9]+"),
         dim = stri_extract_first_regex(par_2,"[0-9]+")) %>%
  select(-c("par_1","par_2")) %>%
  pivot_wider(names_from = dim, values_from = med) %>%
  mutate(job1 = job[,1],
         job2 = job[,2],
         job3 = job[,3]) %>%
  pivot_longer(cols = c(job1,job2,job3),names_to = "time",names_prefix = "job") %>% 
  mutate(class = labs[value]) %>%
  select(-value) 
med_w <- data.frame(par = rownames(fit_summ), med = fit_summ[,4]) %>%
  filter(grepl("w\\[", par)) %>%
  cSplit("par",direction = "wide") %>%
  mutate(class = stri_extract_first_regex(par_1,"[0-9]+"),
         time = stri_extract_first_regex(par_2,"[0-9]+"),
         dim = stri_extract_first_regex(par_3,"[0-9]+")) %>%
  select(-c("par_1","par_2","par_3"))%>%
  pivot_wider(names_from = dim, values_from = med) %>%
  mutate(class = labs[as.numeric(class)])
ggplot() +  geom_point(data = med_z, aes(x = `1`, y = `2`, color = class, alpha = 0.5)) + 
  geom_point(data = med_w, aes(x = `1`, y = `2`, fill = class), 
             shape = 25, size = 4, color = "black")  +
  facet_wrap(~time) + 
  ggtitle("2.5th quantile of latent space positions")
```

```{r,echo=F}
med_z <- data.frame(par = rownames(fit_summ), med = fit_summ[,5]) %>%
  filter(grepl("z\\[", par)) %>%
  cSplit("par",direction = "wide") %>%
  mutate(worker = stri_extract_first_regex(par_1,"[0-9]+"),
         dim = stri_extract_first_regex(par_2,"[0-9]+")) %>%
  select(-c("par_1","par_2")) %>%
  pivot_wider(names_from = dim, values_from = med) %>%
  mutate(job1 = job[,1],
         job2 = job[,2],
         job3 = job[,3]) %>%
  pivot_longer(cols = c(job1,job2,job3),names_to = "time",names_prefix = "job") %>% 
  mutate(class = labs[value]) %>%
  select(-value) 
med_w <- data.frame(par = rownames(fit_summ), med = fit_summ[,5]) %>%
  filter(grepl("w\\[", par)) %>%
  cSplit("par",direction = "wide") %>%
  mutate(class = stri_extract_first_regex(par_1,"[0-9]+"),
         time = stri_extract_first_regex(par_2,"[0-9]+"),
         dim = stri_extract_first_regex(par_3,"[0-9]+")) %>%
  select(-c("par_1","par_2","par_3"))%>%
  pivot_wider(names_from = dim, values_from = med) %>%
  mutate(class = labs[as.numeric(class)])
ggplot() +  geom_point(data = med_z, aes(x = `1`, y = `2`, color = class, alpha = 0.5)) + 
  geom_point(data = med_w, aes(x = `1`, y = `2`, fill = class), 
             shape = 25, size = 4, color = "black")  +
  facet_wrap(~time) + 
  ggtitle("25th quantile of latent space positions")
```

```{r,echo=F}
med_z <- data.frame(par = rownames(fit_summ), med = fit_summ[,7]) %>%
  filter(grepl("z\\[", par)) %>%
  cSplit("par",direction = "wide") %>%
  mutate(worker = stri_extract_first_regex(par_1,"[0-9]+"),
         dim = stri_extract_first_regex(par_2,"[0-9]+")) %>%
  select(-c("par_1","par_2")) %>%
  pivot_wider(names_from = dim, values_from = med) %>%
  mutate(job1 = job[,1],
         job2 = job[,2],
         job3 = job[,3]) %>%
  pivot_longer(cols = c(job1,job2,job3),names_to = "time",names_prefix = "job") %>% 
  mutate(class = labs[value]) %>%
  select(-value) 
med_w <- data.frame(par = rownames(fit_summ), med = fit_summ[,7]) %>%
  filter(grepl("w\\[", par)) %>%
  cSplit("par",direction = "wide") %>%
  mutate(class = stri_extract_first_regex(par_1,"[0-9]+"),
         time = stri_extract_first_regex(par_2,"[0-9]+"),
         dim = stri_extract_first_regex(par_3,"[0-9]+")) %>%
  select(-c("par_1","par_2","par_3"))%>%
  pivot_wider(names_from = dim, values_from = med) %>%
  mutate(class = labs[as.numeric(class)])
ggplot() +  geom_point(data = med_z, aes(x = `1`, y = `2`, color = class, alpha = 0.5)) + 
  geom_point(data = med_w, aes(x = `1`, y = `2`, fill = class), 
             shape = 25, size = 4, color = "black")  +
  facet_wrap(~time) + 
  ggtitle("75th quantile of latent space positions")
```

```{r,echo=F}
med_z <- data.frame(par = rownames(fit_summ), med = fit_summ[,8]) %>%
  filter(grepl("z\\[", par)) %>%
  cSplit("par",direction = "wide") %>%
  mutate(worker = stri_extract_first_regex(par_1,"[0-9]+"),
         dim = stri_extract_first_regex(par_2,"[0-9]+")) %>%
  select(-c("par_1","par_2")) %>%
  pivot_wider(names_from = dim, values_from = med) %>%
  mutate(job1 = job[,1],
         job2 = job[,2],
         job3 = job[,3]) %>%
  pivot_longer(cols = c(job1,job2,job3),names_to = "time",names_prefix = "job") %>% 
  mutate(class = labs[value]) %>%
  select(-value) 
med_w <- data.frame(par = rownames(fit_summ), med = fit_summ[,8]) %>%
  filter(grepl("w\\[", par)) %>%
  cSplit("par",direction = "wide") %>%
  mutate(class = stri_extract_first_regex(par_1,"[0-9]+"),
         time = stri_extract_first_regex(par_2,"[0-9]+"),
         dim = stri_extract_first_regex(par_3,"[0-9]+")) %>%
  select(-c("par_1","par_2","par_3"))%>%
  pivot_wider(names_from = dim, values_from = med) %>%
  mutate(class = labs[as.numeric(class)])
ggplot() +  geom_point(data = med_z, aes(x = `1`, y = `2`, color = class, alpha = 0.5)) + 
  geom_point(data = med_w, aes(x = `1`, y = `2`, fill = class), 
             shape = 25, size = 4, color = "black")  +
  facet_wrap(~time) + 
  ggtitle("97.5th quantile of latent space positions")
```


